# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       asio

# >> macros
# << macros

Summary:    ASIO library
Version:    1.14.0
Release:    0
Group:      Qt/Qt
License:    ASL 2.0
URL:        https://www.resiprocate.org/
Source0:    resiprocate-1.12.0.tar.gz
Source100:  asio.yaml
Source101:  asio-rpmlintrc
BuildRequires:  pkgconfig(libcrypto)
BuildRequires:  pkgconfig(python3)
BuildRequires:  pkgconfig

%description
%{summary}.

%if "%{?vendor}" == "chum"
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/resiprocate/resiprocate
PackageIcon: https://avatars.githubusercontent.com/u/2827263?s=48&v=4
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n resiprocate-resiprocate-1.12.0

# >> setup
# << setup

%build
# >> build pre
pushd contrib/asio
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
pushd contrib/asio
# << install pre
%make_install

# >> install post
popd
# << install post

%files
%defattr(-,root,root,-)
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/asio
%{_includedir}/asio.hpp
# >> files devel
# << files devel
