# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       libsipXport

# >> macros
# << macros
%define keepstatic 1
%define extraver 20231108
%define sover 2

Summary:    OS Abstraction and OS Utilities library for sipX modules
Version:    3.3.0
Release:    0
Group:      Development/Libraries
License:    Pingtel Commercial License
URL:        https://github.com/sipXtapi/sipXtapi
Source0:    sipXtapi-%{version}_%{extraver}.tar.xz
Source100:  libsipXport.yaml
Source101:  libsipXport-rpmlintrc
Patch0:     0003-pcre-patch.patch
BuildRequires:  pkgconfig(opus)
BuildRequires:  pkgconfig(speex)
BuildRequires:  pkgconfig(speexdsp)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libpcre)

%description
%{summary}

%if "%{?vendor}" == "chum"
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: %{url}
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
%endif


%package devel
Summary:    Header files and library symbolic links for %{name}
Group:      Development
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n sipXtapi-%{version}_%{extraver}

# 0003-pcre-patch.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
export CFLAGS="${CFLAGS} %{optflags} -fPIC"
export CXXFLAGS="${CXXFLAGS} %{optflags} -fPIC"
export LD_AS_NEEDED=1


pushd sipXportLib
autoupdate
%reconfigure \
--prefix=%{_prefix} \
--includedir=%{_includedir}/%{name} \
--disable-shared \
--enable-static \
--with-gnu-ld \
--without-openssl \
--without-cppunit \
--disable-buildnumber \
--disable-doxygen
# << build pre



# >> build post

%make_build
popd
find . -name "*.so*"
#ls -l */src/.libs

# << build post

%install
rm -rf %{buildroot}
# >> install pre
pushd sipXportLib
#%%make_install
make DESTDIR=%{buildroot} INSTALL_ROOT=%{buildroot} install
popd
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/syslogviewer
%{_bindir}/sipx-upgrade
%{_bindir}/sipx-config
%{_libdir}/%{name}.la
%{_libdir}/libsipXunit.la
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_bindir}/sipxportlib-config
%{_libdir}/%{name}.a
%{_libdir}/libsipXunit.a
%{_includedir}/%{name}
%exclude %{_includedir}/%{name}/xmlparser
# >> files devel
# << files devel
