# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       libsipXtack

# >> macros
# << macros
%define keepstatic 1
%define extraver 20231108
%define sover 2

Summary:    This project provides an RFC 3261, 3263 complient SIP stack
Version:    3.3.0
Release:    0
Group:      Development/Libraries
License:    Pingtel Commercial License
URL:        https://github.com/sipXtapi/sipXtapi
Source0:    sipXtapi-%{version}_%{extraver}.tar.xz
Source100:  libsipXtack.yaml
Source101:  libsipXtack-rpmlintrc
Patch0:     0003-pcre-patch.patch
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(opus)
BuildRequires:  pkgconfig(speex)
BuildRequires:  pkgconfig(speexdsp)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libpcre)
BuildRequires:  libsipXport-devel
BuildRequires:  libsipXsdp-devel

%description
%{summary}

%if "%{?vendor}" == "chum"
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: %{url}
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
%endif


%package devel
Summary:    Header files and library symbolic links for %{name}
Group:      Development
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n sipXtapi-%{version}_%{extraver}

# 0003-pcre-patch.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre

pushd sipXtackLib
%reconfigure \
--disable-shared \
--enable-static \
--prefix=%{_prefix} \
--includedir=%{_includedir}/%{name} \
--without-openssl \
--without-cppunit \
--disable-doxygen \
--disable-sipviewer

# --with-sipxportinc=<dir>
# --with-sipxportlib=<dir>
# --with-sipxsdpinc=<dir>
# --with-sipxsdplib=<dir>
# --with-sipxtackinc=<dir>
# --with-sipxtacklib=<dir>
#--with-sipxportinc=%%{_includedir}/libsipXport \
#--with-sipxportlib=%%{_libdir} \
#--with-sipxsdpinc=%%{_includedir}/libsipXsdp \
#--with-sipxsdplib=%%{_libdir} \



# << build pre



# >> build post

%make_build
popd
find . -name "*.so*"
#ls -l */src/.libs

# << build post

%install
rm -rf %{buildroot}
# >> install pre
pushd sipXtackLib
#%%make_install
make DESTDIR=%{buildroot} INSTALL_ROOT=%{buildroot} install
popd
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/basicImClient
%{_bindir}/siplog2siptrace
%{_bindir}/siptest
%{_bindir}/siptrace-merge
%{_bindir}/subscribe-dialog-test
%{_bindir}/syslog2siptrace
%{_libdir}/%{name}.la
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_bindir}/sipxtacklib-config
%{_libdir}/%{name}.a
%{_includedir}/%{name}
%dir %{_datadir}/sipx
%{_datadir}/sipx/schema/sip_types.xsd
# >> files devel
# << files devel
