# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       opensigcomp

# >> macros
# << macros
%define keepstatic 1

Summary:    opensigcomp library
Version:    0.9.6
Release:    0
Group:      Qt/Qt
License:    ASL 2.0
URL:        https://www.resiprocate.org/
Source0:    resiprocate-1.12.0.tar.gz
Source100:  opensigcomp.yaml
Source101:  opensigcomp-rpmlintrc
BuildRequires:  pkgconfig(libcrypto)
BuildRequires:  perl

%description
%{summary}.

%if "%{?vendor}" == "chum"
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/resiprocate/resiprocate
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development

%description devel
%{summary}.

%prep
%setup -q -n resiprocate-resiprocate-1.12.0

# >> setup
# << setup

%build
# >> build pre
pushd contrib/%{name}
export CFLAGS="${CFLAGS} -Wno-error=write-strings -Wno-error=unused-but-set-variable -Wno-error=aggressive-loop-optimizations -Wno-error=overflow -w"
export CXXFLAGS="${CXXFLAGS} -Wno-error=write-strings -Wno-error=unused-but-set-variable -Wno-error=aggressive-loop-optimizations -Wno-error=overflow -w"

./configure -y --prefix=%{_prefix}
make -C src %{?_smp_mflags} libopensigcomp.a
# << build pre



# >> build post
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
pushd contrib/%{name}
make -C src INSTALL_LIB=%{buildroot}%{_libdir} INSTALL_INC=%{buildroot}%{_includedir}/%{name}/osc INSTALL_ROOT=%{buildroot} PREFIX=%{_prefix} install
# << install pre

# >> install post
popd
# << install post


%files devel
%defattr(-,root,root,-)
%{_includedir}/%{name}
%{_libdir}/*.a
# >> files devel
# << files devel
